import json, subprocess, base64, re
C=json.load(open("candidates.json"))
sel=[r for r in C if r.get("gfi",0)+r.get("hw",0)>0 and r.get("contributing") and (r.get("last_merge") or "")>="2026-07-01"
     and r["lang"] in ("Python","Jupyter Notebook","Julia") and r["prs"]<60 and r["org"]!="NOAA-GFDL"]
sel.sort(key=lambda r:-(r["gfi"]+r["hw"]))
print(len(sel),"para triar")
pat={"CLA":r"\bCLA\b|contributor license","DCO":r"signed-off|sign-off|\bDCO\b|Developer Certificate","AI":r"\bAI\b|\bLLM|artificial intelligence|copilot|generated by|agent","CONTACT":r"contact us|reach out before|discuss first|open an issue first"}
res=[]
for r in sel[:60]:
    txt=""
    for path in ("CONTRIBUTING.md",".github/CONTRIBUTING.md","docs/CONTRIBUTING.md","CONTRIBUTING.rst"):
        p=subprocess.run(["gh","api",f"repos/{r['name']}/contents/{path}","--jq",".content"],capture_output=True,text=True)
        if p.returncode==0 and p.stdout.strip():
            txt=base64.b64decode(p.stdout.strip()).decode("utf8","ignore"); break
    flags=[k for k,v in pat.items() if re.search(v,txt,re.I)]
    res.append((r["name"],r["lang"],r["gfi"],r["hw"],r["prs"],flags,len(txt)))
for x in res: print(x)
