"""Built-in template: pressure relief valve datasheet, with the data API 520 Part I (sizing) and API 526 (flanged steel
valves) ask for. The output is a compiled datasheet generated by the tool, not a reproduction of a standard's form.

Data usually comes from the process datasheet or the relief load summary (relieving case, rate, fluid properties),
the PSV sizing calculation (orifice) and the piping/valve specifications (connections, materials).
"""
from __future__ import annotations

from ..spec import Field as _f
from ..spec import FormSpec

__all__ = ["SPEC"]

G, S, P, C, M = "General", "Service conditions", "Pressures", "Sizing", "Connections and materials"

ORIFICES = ("D", "E", "F", "G", "H", "J", "K", "L", "M", "N", "P", "Q", "R", "T")

FIELDS = [
    _f("tag", "Tag number", G, patterns=(r"tag(?: no\.?| number)?", r"psv (?:tag|no\.?|number)", r"item no\.?"),
       required=True),
    _f("service", "Service", G, patterns=(r"service",)),
    _f("protected_equipment", "Protected equipment", G, patterns=(r"protected (?:equipment|system)", r"equipment protected"),
       required=True, source_hint="relief load summary"),
    _f("line_number", "Line number", G, patterns=(r"line (?:no\.?|number)",)),
    _f("pid", "P&ID", G, patterns=(r"p&id(?: no\.?| number)?", r"p ?& ?id")),
    _f("quantity", "Quantity", G, kind="number", patterns=(r"quantity", r"qty", r"number of valves")),
    _f("design_code", "Design code", G, patterns=(r"design code", r"code"), source_hint="valve specification"),
    _f("valve_type", "Valve type", G, kind="choice", options=("conventional", "balanced bellows", "pilot operated"),
       aliases={"conventional": r"conventional|spring[- ]loaded(?!.*bellows)", "balanced bellows": r"bellows|balanced",
                "pilot operated": r"pilot"}, patterns=(r"valve type", r"type of valve", r"psv type", r"design type"),
       required=True),
    _f("governing_case", "Governing relief case", G, kind="choice",
       options=("fire", "blocked outlet", "control valve failure", "thermal expansion", "tube rupture",
                "power failure", "other"), other="other",
       aliases={"fire": r"\bfire\b", "blocked outlet": r"blocked (?:outlet|discharge)",
                "control valve failure": r"control valve|cv failure", "thermal expansion": r"thermal",
                "tube rupture": r"tube rupture|tube failure", "power failure": r"power failure|loss of power"},
       patterns=(r"governing (?:relief )?case", r"relief case", r"sizing case", r"design case"), required=True,
       source_hint="relief load summary"),
    # service conditions
    _f("fluid", "Fluid", S, patterns=(r"fluid", r"relieved fluid", r"fluid name"), required=True,
       source_hint="process datasheet"),
    _f("fluid_state", "Fluid state", S, kind="choice", options=("gas", "liquid", "two-phase", "steam"),
       aliases={"gas": r"\bgas\b|\bvapou?r\b", "two-phase": r"two[- ]phase|2[- ]phase|flashing",
                "steam": r"\bsteam\b"},
       patterns=(r"fluid state", r"phase", r"fluid phase"), required=True),
    _f("relieving_rate", "Required relieving capacity", S, kind="quantity", quantity="mass flow",
       patterns=(r"required (?:relieving )?(?:capacity|rate|flow)", r"relieving (?:rate|capacity|load)",
                 r"relief (?:rate|load)"), required=True, source_hint="relief load summary"),
    _f("molecular_weight", "Molecular weight", S, kind="number", patterns=(r"molecular weight", r"mol\.? ?wt\.?", r"\bmw\b")),
    _f("k_ratio", "Ratio of specific heats (k = Cp/Cv)", S, kind="number",
       patterns=(r"ratio of specific heats", r"cp ?/ ?cv", r"specific heat ratio", r"\bk\b(?: ?\(cp/cv\))?")),
    _f("z_factor", "Compressibility factor Z", S, kind="number", patterns=(r"compressibility(?: factor)?(?: z)?", r"\bz\b")),
    _f("density", "Density at relieving conditions", S, kind="quantity", quantity="density",
       patterns=(r"(?:relieving )?density", r"liquid density")),
    _f("specific_gravity", "Specific gravity", S, kind="number", patterns=(r"specific gravity", r"\bs\.?g\.?\b")),
    _f("viscosity", "Viscosity at relieving conditions", S, kind="quantity", quantity="viscosity",
       patterns=(r"viscosity",)),
    _f("operating_temp", "Operating temperature", S, kind="quantity", quantity="temperature",
       patterns=(r"operating temperature", r"normal temperature")),
    _f("relieving_temp", "Relieving temperature", S, kind="quantity", quantity="temperature",
       patterns=(r"relieving temperature", r"relief temperature"), required=True),
    # pressures
    _f("operating_pressure", "Operating pressure", P, kind="quantity", quantity="pressure",
       patterns=(r"operating pressure", r"normal (?:operating )?pressure")),
    _f("set_pressure", "Set pressure", P, kind="quantity", quantity="pressure",
       patterns=(r"set pressure", r"opening pressure"), required=True),
    _f("mawp", "MAWP of the protected equipment", P, kind="quantity", quantity="pressure",
       patterns=(r"mawp", r"design pressure(?: of (?:the )?protected equipment)?", r"maximum allowable working pressure")),
    _f("overpressure", "Allowable overpressure", P, patterns=(r"(?:allowable )?overpressure", r"accumulation"),
       required=True),
    _f("cdtp", "Cold differential test pressure", P, kind="quantity", quantity="pressure",
       patterns=(r"cold differential test pressure", r"\bcdtp\b")),
    _f("bp_superimposed", "Back pressure, superimposed", P, kind="quantity", quantity="pressure",
       patterns=(r"superimposed back ?pressure", r"back ?pressure,? superimposed")),
    _f("bp_built_up", "Back pressure, built-up", P, kind="quantity", quantity="pressure",
       patterns=(r"built[- ]up back ?pressure", r"back ?pressure,? built[- ]up")),
    _f("bp_total", "Back pressure, total", P, kind="quantity", quantity="pressure",
       patterns=(r"total back ?pressure", r"back ?pressure,? total", r"back ?pressure")),
    # sizing
    _f("area_required", "Calculated orifice area", C, kind="quantity", quantity="area",
       patterns=(r"(?:calculated|required|effective) (?:orifice |discharge )?area",), source_hint="PSV sizing calculation"),
    _f("orifice", "Selected orifice (API 526 letter)", C, kind="choice", options=ORIFICES,
       aliases={o: rf"(?<![A-Za-z]){o}(?![A-Za-z])" for o in ORIFICES},
       patterns=(r"(?:selected )?orifice(?: designation| letter| size)?",), required=True,
       source_hint="PSV sizing calculation"),
    _f("area_selected", "Selected orifice area", C, kind="quantity", quantity="area",
       patterns=(r"(?:selected|actual|api) orifice area", r"orifice area")),
    _f("rated_capacity", "Rated capacity", C, kind="quantity", quantity="mass flow",
       patterns=(r"rated (?:relieving )?capacity", r"certified capacity")),
    _f("kd", "Effective coefficient of discharge Kd", C, kind="number",
       patterns=(r"(?:effective )?coefficient of discharge", r"\bkd\b")),
    # connections and materials
    _f("inlet", "Inlet size and rating", M, patterns=(r"inlet(?: size)?(?: and rating)?", r"inlet connection"),
       required=True, source_hint="valve specification"),
    _f("outlet", "Outlet size and rating", M, patterns=(r"outlet(?: size)?(?: and rating)?", r"outlet connection"),
       required=True, source_hint="valve specification"),
    _f("facing", "Flange facing", M, patterns=(r"(?:flange )?facing",)),
    _f("body_material", "Body and bonnet material", M, patterns=(r"body(?: and bonnet)? material", r"body", r"body/bonnet")),
    _f("trim_material", "Nozzle and disc material", M, patterns=(r"(?:nozzle(?: and |\s?/\s?)disc|trim) material", r"trim",
                                                                    r"nozzle\s?/\s?disc")),
    _f("spring_material", "Spring material", M, patterns=(r"spring(?: material)?",)),
    _f("bellows_material", "Bellows material", M, patterns=(r"bellows(?: material)?",)),
    _f("lifting_lever", "Lifting lever", M, kind="bool", patterns=(r"lifting lever", r"lever")),
    _f("test_gag", "Test gag", M, kind="bool", patterns=(r"test gag", r"gag")),
]

SPEC = FormSpec(
    id="psv", title="Pressure relief valve datasheet", standard="API 520 Part I / API 526 data",
    summary="Relief case, rate, fluid properties, pressures, orifice, connections and materials of one PSV.",
    description="A pressure relief valve (PSV) datasheet: relieving case and capacity, fluid properties at relieving "
                "conditions, set pressure and back pressures, the API 526 orifice, connections and materials.",
    inputs=("process datasheet", "relief load summary", "PSV sizing calculation", "valve specification", "other"),
    fields=FIELDS, filename_key="tag")
