"""Built-in template: centrifugal pump datasheet, with the data API 610 asks the purchaser for. The output is a
compiled datasheet generated by the tool, not a reproduction of the standard's data sheet.

Liquid and operating data usually comes from the process datasheet and the hydraulic calculation (NPSH available);
construction choices from the client's pump specification; site and driver data from the electrical and site
specifications.
"""
from __future__ import annotations

from ..spec import Field as _f
from ..spec import FormSpec

__all__ = ["SPEC"]

G, LQ, OP, CO, DR = "General", "Liquid", "Operating conditions", "Construction", "Driver and site"

FIELDS = [
    _f("tag", "Item number", G, patterns=(r"item no\.?", r"tag(?: no\.?| number)?", r"pump (?:no\.?|number|tag)",
                                          r"equipment (?:no\.?|number|tag)"), required=True),
    _f("service", "Service", G, patterns=(r"service",), required=True),
    _f("quantity", "Pumps required (operating + spare)", G, patterns=(r"(?:no\.? of |number of )?pumps(?: required)?",
                                                                      r"quantity", r"operating ?/ ?spare")),
    _f("pump_type", "Pump type (API 610)", G, patterns=(r"pump type", r"api 610 type", r"type \(api 610\)"),
       required=True, source_hint="pump specification"),
    _f("design_code", "Design code", G, patterns=(r"design code", r"code"), source_hint="client specification"),
    # liquid
    _f("liquid", "Liquid", LQ, patterns=(r"liquid(?: type| name)?", r"fluid(?: pumped)?", r"pumped (?:liquid|fluid)"),
       required=True, source_hint="process datasheet"),
    _f("pumping_temp", "Pumping temperature, normal", LQ, kind="quantity", quantity="temperature",
       patterns=(r"(?:normal )?pumping temperature", r"pumping temperature,? normal", r"operating temperature"),
       required=True),
    _f("pumping_temp_max", "Pumping temperature, maximum", LQ, kind="quantity", quantity="temperature",
       patterns=(r"max(?:imum)? pumping temperature", r"pumping temperature,? max(?:imum)?")),
    _f("sg", "Specific gravity at pumping temperature", LQ, kind="number",
       patterns=(r"specific gravity", r"\bs\.?g\.?\b", r"relative density"), required=True),
    _f("viscosity", "Viscosity at pumping temperature", LQ, kind="quantity", quantity="viscosity",
       patterns=(r"viscosity",), required=True),
    _f("vapor_pressure", "Vapor pressure at pumping temperature", LQ, kind="quantity", quantity="pressure",
       patterns=(r"vapou?r pressure",), required=True),
    _f("hazardous_liquid", "Hazardous or flammable liquid", LQ, kind="bool",
       patterns=(r"hazardous(?: liquid)?", r"flammable(?: liquid)?", r"toxic")),
    _f("solids", "Solids / corrosive agents", LQ, patterns=(r"solids(?: content)?", r"corrosive agents?",
                                                            r"chlorides?")),
    # operating conditions
    _f("flow_rated", "Rated flow", OP, kind="quantity", quantity="volume flow",
       patterns=(r"rated (?:flow|capacity)", r"flow,? rated", r"design flow"), required=True,
       source_hint="process datasheet"),
    _f("flow_normal", "Normal flow", OP, kind="quantity", quantity="volume flow",
       patterns=(r"normal (?:flow|capacity)", r"flow,? normal")),
    _f("flow_min", "Minimum flow", OP, kind="quantity", quantity="volume flow",
       patterns=(r"min(?:imum)? (?:continuous )?(?:stable )?flow", r"flow,? min(?:imum)?")),
    _f("p_suction", "Suction pressure, rated", OP, kind="quantity", quantity="pressure",
       patterns=(r"(?:rated )?suction pressure", r"suction pressure,? rated"), required=True),
    _f("p_suction_max", "Suction pressure, maximum", OP, kind="quantity", quantity="pressure",
       patterns=(r"max(?:imum)? suction pressure", r"suction pressure,? max(?:imum)?")),
    _f("p_discharge", "Discharge pressure", OP, kind="quantity", quantity="pressure",
       patterns=(r"(?:rated )?discharge pressure",), required=True),
    _f("dp", "Differential pressure", OP, kind="quantity", quantity="pressure", patterns=(r"differential pressure",)),
    _f("head", "Differential head", OP, kind="quantity", quantity="length",
       patterns=(r"(?:differential |total |rated )?head",), required=True),
    _f("npsha", "NPSH available", OP, kind="quantity", quantity="length",
       patterns=(r"npsh ?a(?:vailable)?", r"npsh available", r"net positive suction head available"), required=True,
       source_hint="hydraulic calculation"),
    _f("npshr", "NPSH required", OP, kind="quantity", quantity="length",
       patterns=(r"npsh ?r(?:equired)?", r"npsh required", r"npsh3")),
    _f("efficiency", "Efficiency", OP, patterns=(r"(?:pump )?efficiency",)),
    _f("power_rated", "Rated power", OP, kind="quantity", quantity="power",
       patterns=(r"rated power", r"(?:pump )?(?:absorbed|shaft|brake) power", r"\bbkw\b")),
    _f("speed", "Speed", OP, kind="quantity", quantity="frequency", patterns=(r"(?:rated )?speed",)),
    _f("service_type", "Duty (continuous / intermittent)", OP, kind="choice", options=("continuous", "intermittent", "standby"),
       patterns=(r"(?:operation|service) type", r"duty")),
    # construction
    _f("impeller_dia", "Impeller diameter (rated)", CO, kind="quantity", quantity="length",
       patterns=(r"impeller diameter(?:,? rated)?", r"rated impeller")),
    _f("nozzle_suction", "Suction nozzle (size, rating, facing)", CO, patterns=(r"suction (?:nozzle|connection)",)),
    _f("nozzle_discharge", "Discharge nozzle (size, rating, facing)", CO,
       patterns=(r"discharge (?:nozzle|connection)",)),
    _f("material_class", "Material class (API 610 Annex H)", CO,
       patterns=(r"material class", r"materials? \(api 610\)", r"api material class"), required=True,
       source_hint="pump specification"),
    _f("casing_material", "Casing material", CO, patterns=(r"casing(?: material)?",)),
    _f("impeller_material", "Impeller material", CO, patterns=(r"impeller material",)),
    _f("seal", "Mechanical seal (API 682 category / arrangement)", CO,
       patterns=(r"(?:mechanical )?seal(?: type| arrangement)?", r"api 682"), required=True),
    _f("seal_plan", "Seal flush plan", CO, patterns=(r"(?:seal )?(?:flush(?:ing)? )?plan", r"api plan")),
    _f("baseplate", "Baseplate", CO, patterns=(r"baseplate",)),
    # driver and site
    _f("driver", "Driver type", DR, kind="choice", options=("electric motor", "steam turbine", "diesel engine"),
       aliases={"electric motor": r"motor|electric", "steam turbine": r"turbine", "diesel engine": r"diesel|engine"},
       patterns=(r"driver(?: type)?",), required=True),
    _f("motor_rating", "Motor rating", DR, kind="quantity", quantity="power",
       patterns=(r"motor (?:rating|power|size)", r"driver (?:rating|power)")),
    _f("power_supply", "Power supply (V / phase / Hz)", DR, patterns=(r"power supply", r"electrical supply",
                                                                      r"voltage")),
    _f("area_class", "Hazardous area classification", DR,
       patterns=(r"(?:hazardous )?area classification", r"electrical area classification", r"zone classification"),
       required=True, source_hint="site data"),
    _f("ambient", "Ambient temperature range", DR, patterns=(r"ambient temperature(?: range)?",)),
    _f("location", "Location (indoor / outdoor)", DR, patterns=(r"location", r"installation")),
]

SPEC = FormSpec(
    id="pump", title="Centrifugal pump datasheet", standard="API 610 data",
    summary="Liquid properties, rated and normal flow, pressures, head, NPSH, construction, seal and driver.",
    description="An API 610 centrifugal pump datasheet: liquid and its properties at pumping temperature, rated and "
                "normal flow, suction and discharge pressures, head, NPSH available, pump type, materials, seal and "
                "driver, hazardous area.",
    inputs=("process datasheet", "hydraulic calculation", "pump specification", "site data", "other"),
    fields=FIELDS, filename_key="tag")
