"""Built-in template: shell-and-tube heat exchanger datasheet, with the data a TEMA specification sheet and API 660 ask
for. The output is a compiled datasheet generated by the tool, not a reproduction of a standard's form.

Process data (fluids, flows, temperatures, pressures, fouling) usually comes from the process datasheet, one column per
side; construction data from the mechanical datasheet and the client's specifications. Tables with a "shell side" and
a "tube side" column are read cell by cell.
"""
from __future__ import annotations

from ..spec import Field as _f
from ..spec import FormSpec

__all__ = ["SPEC"]

G, PR, DS, CO = "General", "Performance (per side)", "Design (per side)", "Construction"
SIDES = {"shell": (r"shell(?: side)?|\bs/s\b", "shell side"), "tube": (r"tube(?: side)?|\bt/s\b", "tube side")}


def _sided(key, label, section, row, kind="quantity", quantity=None, required=(), hint=""):
    """One item per side. ``row`` are the row-label phrasings without side words."""
    out = []
    for side, (rx, name) in SIDES.items():
        pats = tuple(rf"(?:{rx})[ ,:-]*{r}" for r in row) + tuple(rf"{r}[ ,:-]*\(?(?:{rx})\)?" for r in row)
        out.append(_f(f"{side}_{key}", f"{label}, {name}", section, kind=kind, quantity=quantity, patterns=pats,
                      row_patterns=tuple(row), column=side, required=side in required, source_hint=hint))
    return out


FIELDS = [
    _f("tag", "Item number", G, patterns=(r"item no\.?", r"item number", r"tag(?: no\.?| number)?",
                                          r"equipment (?:no\.?|number|tag)"), required=True),
    _f("service", "Service", G, patterns=(r"service",), required=True),
    _f("tema_type", "TEMA type", G, patterns=(r"tema type", r"type \(tema\)", r"exchanger type"), required=True),
    _f("tema_class", "TEMA class", G, kind="choice", options=("R", "C", "B"),
       aliases={o: rf"(?<![A-Za-z]){o}(?![A-Za-z])" for o in "RCB"}, patterns=(r"tema class",), required=True,
       source_hint="client specification"),
    _f("orientation", "Orientation", G, kind="choice", options=("horizontal", "vertical"),
       patterns=(r"orientation", r"position"), required=True),
    _f("size", "Size (shell ID x tube length)", G, patterns=(r"size",)),
    _f("shells", "Shells (series / parallel)", G, patterns=(r"(?:no\.? of |number of )?shells(?: per unit)?",
                                                            r"connected in")),
    _f("duty", "Heat duty", G, kind="quantity", quantity="power", patterns=(r"(?:heat )?duty", r"heat exchanged"),
       required=True, source_hint="process datasheet"),
    _f("surface", "Surface area per shell", G, kind="quantity", quantity="area",
       patterns=(r"(?:effective )?surface(?: area)?(?: per shell)?", r"heat transfer area")),
    _f("design_code", "Design code", G, patterns=(r"design code", r"code(?: requirements)?"), required=True,
       source_hint="client specification"),
    *_sided("fluid", "Fluid", PR, (r"fluid(?: name)?", r"fluid allocation"), kind="text", required=("shell", "tube"),
            hint="process datasheet"),
    *_sided("flow", "Total flow", PR, (r"(?:total )?(?:fluid )?flow(?: rate)?", r"mass flow"), quantity="mass flow",
            required=("shell", "tube"), hint="process datasheet"),
    *_sided("t_in", "Temperature in", PR, (r"(?:inlet )?temperature,? in(?:let)?", r"inlet temperature", r"temp\.? in"),
            quantity="temperature", required=("shell", "tube")),
    *_sided("t_out", "Temperature out", PR, (r"(?:outlet )?temperature,? out(?:let)?", r"outlet temperature",
                                             r"temp\.? out"), quantity="temperature", required=("shell", "tube")),
    *_sided("p_op", "Operating pressure (inlet)", PR, (r"(?:inlet )?operating pressure", r"operating pressure,? inlet")
            , quantity="pressure"),
    *_sided("dp_allow", "Pressure drop, allowable", PR, (r"(?:allowable|allow\.) pressure drop",
                                                         r"pressure drop,? allow(?:able|\.)"), quantity="pressure"),
    *_sided("dp_calc", "Pressure drop, calculated", PR, (r"(?:calculated|calc\.) pressure drop",
                                                         r"pressure drop,? calc(?:ulated|\.)"), quantity="pressure"),
    *_sided("fouling", "Fouling resistance", PR, (r"fouling(?: resistance| factor)?",), kind="text",
            required=("shell", "tube")),
    *_sided("velocity", "Velocity", PR, (r"velocity",), quantity="speed"),
    *_sided("p_design", "Design pressure", DS, (r"design pressure",), quantity="pressure", required=("shell", "tube"),
            hint="mechanical datasheet"),
    *_sided("t_design", "Design temperature", DS, (r"(?:max\.? )?design temperature",), quantity="temperature",
            required=("shell", "tube"), hint="mechanical datasheet"),
    *_sided("mdmt", "MDMT", DS, (r"mdmt", r"min(?:imum)? design (?:metal )?temperature"), quantity="temperature"),
    *_sided("p_test", "Test pressure", DS, (r"(?:hydro(?:static)? )?test pressure",), quantity="pressure"),
    *_sided("passes", "Number of passes", DS, (r"(?:no\.? of |number of )?passes(?: per shell)?",), kind="number"),
    *_sided("ca", "Corrosion allowance", DS, (r"corrosion allowance", r"c\.a\."), quantity="length",
            required=("shell", "tube"), hint="client specification"),
    *_sided("inlet_nozzle", "Inlet connection", DS, (r"inlet (?:nozzle|connection)",), kind="text"),
    *_sided("outlet_nozzle", "Outlet connection", DS, (r"outlet (?:nozzle|connection)",), kind="text"),
    _f("tube_od", "Tube OD", CO, kind="quantity", quantity="length", patterns=(r"tube (?:od|o\.d\.|outside diameter)",),
       required=True),
    _f("tube_thk", "Tube thickness", CO, patterns=(r"tube (?:thickness|wall(?: thickness)?|gauge)", r"tube bwg"),
       required=True),
    _f("tube_length", "Tube length", CO, kind="quantity", quantity="length", patterns=(r"tube length",), required=True),
    _f("tube_pitch", "Tube pitch", CO, kind="quantity", quantity="length", patterns=(r"(?:tube )?pitch",)),
    _f("tube_layout", "Tube layout angle", CO, kind="choice", options=("30", "45", "60", "90"),
       aliases={a: rf"(?<!\d){a}(?!\d)" for a in ("30", "45", "60", "90")}, patterns=(r"(?:tube )?layout(?: angle)?",
                                                                                        r"tube pattern")),
    _f("tube_count", "Number of tubes", CO, kind="number", patterns=(r"(?:no\.? of |number of )tubes", r"tube count")),
    _f("tube_type", "Tube type", CO, patterns=(r"tube type",)),
    _f("tube_material", "Tube material", CO, patterns=(r"tubes?(?: material)?", r"tube moc"), required=True),
    _f("shell_id", "Shell inside diameter", CO, kind="quantity", quantity="length",
       patterns=(r"shell (?:id|i\.d\.|inside diameter)",), required=True),
    _f("shell_material", "Shell material", CO, patterns=(r"shell(?: material)?", r"shell moc"), required=True),
    _f("channel_material", "Channel material", CO, patterns=(r"channel(?: material)?", r"channel ?/ ?bonnet(?: material)?")),
    _f("tubesheet_material", "Tubesheet material", CO, patterns=(r"tube ?sheets?(?: material)?",)),
    _f("baffle_type", "Baffle type", CO, patterns=(r"baffle type", r"(?:cross )?baffles?")),
    _f("baffle_cut", "Baffle cut", CO, patterns=(r"baffle cut", r"cut \(%d\)")),
    _f("baffle_spacing", "Baffle spacing", CO, kind="quantity", quantity="length", patterns=(r"baffle spacing",)),
    _f("gaskets", "Gaskets", CO, patterns=(r"gaskets?",)),
    _f("weight_empty", "Weight, empty", CO, kind="quantity", quantity="mass", patterns=(r"(?:empty|dry) weight",
                                                                                         r"weight,? empty")),
    _f("weight_full", "Weight, full of water", CO, kind="quantity", quantity="mass",
       patterns=(r"(?:full of water|flooded|test) weight", r"weight,? (?:full|flooded)")),
]

SPEC = FormSpec(
    id="shell_tube", title="Shell-and-tube heat exchanger datasheet", standard="TEMA / API 660 data",
    summary="Fluids, flows, temperatures, pressures and fouling per side; design conditions and construction.",
    description="A shell-and-tube heat exchanger datasheet: process data for the shell side and the tube side, design "
                "conditions per side, TEMA type and class, tubes, shell, baffles and materials.",
    inputs=("process datasheet", "mechanical datasheet", "client specification", "thermal design output", "other"),
    fields=FIELDS, columns={side: rx for side, (rx, _) in SIDES.items()}, filename_key="tag")
