"""Built-in template: atmospheric storage tank datasheet, with the data API 650 asks the purchaser for (Annex L lists
them). The output is a compiled datasheet generated by the tool, not a reproduction of the standard's data sheet.

Process data (product, specific gravity, temperatures, fill and empty rates) usually comes from the process datasheet;
design data from the mechanical datasheet, the client's tank specification and the site data (wind, seismic, snow).
"""
from __future__ import annotations

from ..spec import Field as _f
from ..spec import FormSpec, TableSpec

__all__ = ["SPEC"]

G, PR, DE, CO, LO = "General", "Process", "Design", "Construction and materials", "Site loads"


def _ca(part, pats, required=False):
    return _f(f"ca_{part}", f"Corrosion allowance, {part}", DE, kind="quantity", quantity="length",
              patterns=tuple(rf"{p}[ ,]*(?:corrosion allowance|c\.?a\.?)" for p in pats)
              + tuple(rf"corrosion allowance[ ,:-]*{p}" for p in pats), required=required,
              source_hint="client specification")


FIELDS = [
    _f("tag", "Tag number", G, patterns=(r"tag(?: no\.?| number)?", r"item no\.?", r"tank (?:no\.?|number)",
                                         r"equipment (?:no\.?|number|tag)"), required=True),
    _f("service", "Service", G, patterns=(r"service",), required=True),
    _f("design_code", "Design code", G, patterns=(r"design code", r"code"), required=True,
       source_hint="client specification"),
    _f("location", "Site", G, patterns=(r"site(?: location)?", r"plant location", r"location")),
    # process
    _f("product", "Product stored", PR, patterns=(r"product(?: stored)?", r"stored (?:product|fluid)", r"fluid"),
       required=True, source_hint="process datasheet"),
    _f("sg", "Design specific gravity", PR, kind="number",
       patterns=(r"(?:design )?specific gravity", r"\bs\.?g\.?\b", r"relative density"), required=True),
    _f("vapor_pressure", "Vapor pressure", PR, kind="quantity", quantity="pressure",
       patterns=(r"(?:true )?vapou?r pressure", r"\btvp\b", r"\brvp\b")),
    _f("op_temp", "Operating temperature", PR, kind="quantity", quantity="temperature",
       patterns=(r"(?:normal )?operating temperature",)),
    _f("fill_rate", "Maximum filling rate", PR, kind="quantity", quantity="volume flow",
       patterns=(r"(?:max(?:imum)? )?fill(?:ing)? rate", r"pump[- ]in rate", r"inflow rate"), required=True),
    _f("empty_rate", "Maximum emptying rate", PR, kind="quantity", quantity="volume flow",
       patterns=(r"(?:max(?:imum)? )?empty(?:ing)? rate", r"pump[- ]out rate", r"outflow rate"), required=True),
    _f("nominal_capacity", "Nominal capacity", PR, kind="quantity", quantity="volume",
       patterns=(r"nominal capacity", r"(?:gross|total) capacity", r"capacity"), required=True),
    _f("working_capacity", "Net working capacity", PR, kind="quantity", quantity="volume",
       patterns=(r"(?:net )?working capacity",)),
    # design
    _f("diameter", "Nominal diameter", DE, kind="quantity", quantity="length",
       patterns=(r"(?:nominal |inside )?diameter",), required=True, source_hint="mechanical datasheet"),
    _f("height", "Shell height", DE, kind="quantity", quantity="length", patterns=(r"(?:shell )?height",),
       required=True, source_hint="mechanical datasheet"),
    _f("max_liquid_level", "Maximum design liquid level", DE, kind="quantity", quantity="length",
       patterns=(r"(?:max(?:imum)? )?(?:design )?liquid level", r"\bhhll\b", r"\bmax\.? fill height")),
    _f("design_p", "Design pressure (internal)", DE, kind="quantity", quantity="pressure",
       patterns=(r"(?:internal )?design pressure", r"design pressure,? internal"), required=True),
    _f("design_vac", "Design vacuum (external pressure)", DE, kind="quantity", quantity="pressure",
       patterns=(r"design vacuum", r"(?:external )?design pressure,? external", r"external pressure", r"vacuum"),
       required=True),
    _f("design_t_max", "Maximum design temperature", DE, kind="quantity", quantity="temperature",
       patterns=(r"(?:max(?:imum)? )?design temperature",), required=True),
    _f("dmt", "Design metal temperature (minimum)", DE, kind="quantity", quantity="temperature",
       patterns=(r"design metal temperature", r"\bdmt\b", r"min(?:imum)? design (?:metal )?temperature", r"\bmdmt\b"),
       required=True),
    _ca("shell", (r"shell",), required=True),
    _ca("bottom", (r"bottom",), required=True),
    _ca("roof", (r"roof",)),
    _ca("structure", (r"structur(?:e|al)", r"roof structure")),
    _f("joint_efficiency", "Joint efficiency", DE, kind="number", patterns=(r"joint efficiency",)),
    _f("venting", "Venting basis", DE, patterns=(r"venting(?: basis| standard| design)?", r"vent sizing")),
    # site loads
    _f("wind_code", "Wind design basis", LO, patterns=(r"wind (?:code|standard|design basis)",)),
    _f("wind_speed", "Design wind speed", LO, kind="quantity", quantity="speed",
       patterns=(r"(?:basic |design )?wind speed",), required=True, source_hint="site data"),
    _f("seismic", "Seismic design basis", LO, patterns=(r"seismic(?: design)?(?: basis| code| zone| category)?",),
       required=True, source_hint="site data"),
    _f("snow_load", "Snow load", LO, kind="quantity", quantity="pressure", patterns=(r"snow load",)),
    _f("roof_live_load", "Roof live load", LO, kind="quantity", quantity="pressure", patterns=(r"(?:roof )?live load",)),
    # construction
    _f("roof_type", "Roof type", CO, kind="choice",
       options=("fixed cone", "fixed dome", "external floating", "internal floating", "open top"),
       aliases={"fixed cone": r"cone(?! (?:up|down))", "fixed dome": r"dome|umbrella",
                "external floating": r"external floating|\befr\b|floating roof(?!.*internal)",
                "internal floating": r"internal floating|\bifr\b", "open top": r"open top"},
       match="first", patterns=(r"roof type", r"type of roof", r"roof"), required=True),
    _f("bottom_type", "Bottom type", CO, kind="choice", options=("cone up", "cone down", "flat", "single slope"),
       aliases={"cone up": r"cone up", "cone down": r"cone down", "flat": r"\bflat\b", "single slope": r"single slope"},
       patterns=(r"bottom type", r"type of bottom", r"bottom slope"), required=True),
    _f("annular_plate", "Annular bottom plate", CO, kind="bool", patterns=(r"annular (?:bottom )?plates?",)),
    _f("shell_material", "Shell material", CO, patterns=(r"shell(?: plate)?(?: material)?",), required=True),
    _f("bottom_material", "Bottom material", CO, patterns=(r"bottom(?: plate)?(?: material)?",)),
    _f("roof_material", "Roof material", CO, patterns=(r"roof(?: plate)? material",)),
    _f("foundation", "Foundation type", CO, patterns=(r"foundation(?: type)?",)),
    _f("insulation", "Insulation", CO, kind="bool", patterns=(r"insulat(?:ed|ion)(?: required)?",)),
    _f("heating", "Heating coil", CO, kind="bool", patterns=(r"heating(?: coil)?(?: required)?",)),
    _f("coating", "Coating / painting specification", CO, patterns=(r"coating spec(?:ification)?",
                                                                      r"painting spec(?:ification)?", r"internal lining")),
    _f("hydrotest", "Hydrostatic test medium", CO, patterns=(r"hydro(?:static)? ?test(?: medium| water)?",)),
]

NOZZLES = TableSpec(
    "nozzle", "Nozzle schedule",
    columns={"mark": r"mark|nozzle\s*(?:no|id)|^no\.?$|^tag", "description": r"description|service|purpose",
             "number": r"qty|quantity|number|no\.? req", "size": r"size", "rating": r"class|rating",
             "facing": r"flange|type|facing"},
    header=(r"size", r"nozzle|mark|service|description"), combine={"description": ("mark", "description")},
    defaults={"number": "1"}, description="One row per nozzle or manhole: mark and service, quantity, size, rating.")

SPEC = FormSpec(
    id="tank", title="Atmospheric storage tank datasheet", standard="API 650 data (Annex L)",
    summary="Product, capacities, rates, design conditions, corrosion allowances, site loads, roof and bottom.",
    description="An API 650 atmospheric storage tank datasheet: product and capacities, filling and emptying rates, "
                "design pressure, vacuum and temperatures, corrosion allowances, wind, seismic and snow loads, roof and "
                "bottom types, materials and nozzles.",
    inputs=("process datasheet", "mechanical datasheet", "tank specification", "site data", "other"),
    fields=FIELDS, tables=[NOZZLES], filename_key="tag")
