"""Neural surrogate of the physics engine, used only to *screen* designs.

The finite-volume-resolved physics takes ~40 ms per design; the sizer
needs to screen tens of thousands of candidates per request. A PINNeAPPle
MLP (``ModelRegistry`` + ``Trainer`` + L-BFGS finetune) learns the
base-to-ambient resistance (and pressure drop) over the design space, and
every design it proposes is then re-verified by the physics engine before
it is shown to the user.

One model per cooling mode (forced / natural): they depend on different
variables and a single model would have to learn a discontinuity at
``v = 0``.

Run ``python -m heatsink_sizer.surrogate`` to regenerate the dataset,
retrain and write ``artifacts/surrogate_<mode>.pt`` + its trust report.
"""
from __future__ import annotations

import json
import math
import os
import tempfile
import time
from dataclasses import dataclass
from multiprocessing import Pool
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch

from .engine import DesignInput, OperatingInput, physics_resistance

# trained surrogates and datasets; the HeatSink Sizer app points this at apps/heatsink_sizer/artifacts
ARTIFACTS = os.environ.get("PINNEAPPLE_HEATSINK_ARTIFACTS") or os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..", "apps", "heatsink_sizer", "artifacts"))

# Design space the surrogates are trained (and therefore valid) on. mm, W, C, m/s.
COMMON_RANGES: Dict[str, Tuple[float, float]] = {
    "base_width_mm": (30.0, 200.0),
    "base_depth_mm": (30.0, 200.0),
    "base_thickness_mm": (2.0, 15.0),
    "fin_thickness_mm": (0.6, 4.0),
    "fin_height_mm": (8.0, 80.0),
    "k_w_mk": (150.0, 400.0),
    "source_frac_w": (0.15, 1.0),
    "source_frac_d": (0.15, 1.0),
    "t_ambient_c": (0.0, 50.0),
}
MODE_RANGES: Dict[str, Dict[str, Tuple[float, float]]] = {
    "forced": {"fin_gap_mm": (0.8, 10.0), "air_velocity_m_s": (0.5, 6.0), "power_w": (10.0, 400.0)},
    "natural": {"fin_gap_mm": (2.5, 20.0), "power_w": (1.0, 80.0)},
}
# Materials are generated by conductivity; the physics engine needs a named
# material, so each sample uses the closest one's density and overrides k.
FEATURES = {
    "forced": ["log_W", "log_D", "log_tb", "log_gap", "log_t", "log_H", "log_N", "log_k",
               "log_fw", "log_fd", "T_amb", "log_V", "log_Q"],
    "natural": ["log_W", "log_D", "log_tb", "log_gap", "log_t", "log_H", "log_N", "log_k",
                "log_fw", "log_fd", "T_amb", "log_Q"],
}
TARGETS = {"forced": ["log_R", "log_dP"], "natural": ["log_R"]}


def n_fins_for(width_mm, gap_mm, t_mm):
    return np.maximum(2, np.round((np.asarray(width_mm) + gap_mm) / (np.asarray(t_mm) + gap_mm))).astype(int)


def features(mode: str, W, D, tb, N, t, H, k, sw, sd, Ta, Q, V=None) -> np.ndarray:
    """Vectorised feature map (all arguments broadcastable arrays)."""
    W, D, N, t = map(np.asarray, (W, D, N, t))
    gap = (W - N * t) / np.maximum(N - 1, 1)
    cols = [np.log(W), np.log(D), np.log(tb), np.log(np.maximum(gap, 1e-3)), np.log(t), np.log(H),
            np.log(N), np.log(k), np.log(np.asarray(sw) / W), np.log(np.asarray(sd) / D),
            np.asarray(Ta, dtype=float)]
    if mode == "forced":
        cols.append(np.log(V))
    cols.append(np.log(Q))
    return np.stack([np.broadcast_to(c, np.broadcast(*cols).shape) for c in cols], axis=1).astype(np.float32)


# ── dataset ──────────────────────────────────────────────────────────────────

def _material_for_k(k: float) -> str:
    from pinneapple_physics.closed_form.plate_fin_heatsink import MATERIALS
    return min(MATERIALS, key=lambda m: abs(MATERIALS[m]["k"] - k))


def _one(args) -> Optional[Dict[str, float]]:
    mode, p = args
    from pinneapple_physics.closed_form import plate_fin_heatsink as pfh
    N = int(n_fins_for(p["base_width_mm"], p["fin_gap_mm"], p["fin_thickness_mm"]))
    mat = _material_for_k(p["k_w_mk"])
    old_k = pfh.MATERIALS[mat]["k"]
    pfh.MATERIALS[mat]["k"] = p["k_w_mk"]          # per-process copy of the table
    try:
        d = DesignInput(p["base_width_mm"], p["base_depth_mm"], p["base_thickness_mm"], N,
                        p["fin_thickness_mm"], p["fin_height_mm"], mat)
        o = OperatingInput(power_w=p["power_w"], t_ambient_c=p["t_ambient_c"],
                           air_velocity_m_s=p.get("air_velocity_m_s", 0.0),
                           source_width_mm=p["source_frac_w"] * p["base_width_mm"],
                           source_depth_mm=p["source_frac_d"] * p["base_depth_mm"])
        if d.geometry().fin_gap <= 0:
            return None
        r = physics_resistance(d, o)
    except (ValueError, ArithmeticError):
        return None
    finally:
        pfh.MATERIALS[mat]["k"] = old_k
    row = dict(p, n_fins=N, r_base_k_w=r["r_base_k_w"], pressure_drop_pa=r["pressure_drop_pa"])
    return row if math.isfinite(r["r_base_k_w"]) and r["r_base_k_w"] > 0 else None


def generate_dataset(mode: str, n: int, seed: int = 0, workers: int = 4) -> List[Dict[str, float]]:
    from pinneapple_data.parameter_sampling import sample_parameters
    ranges = {**COMMON_RANGES, **MODE_RANGES[mode]}
    # sample log-uniformly for positive scale parameters
    log_keys = [k for k in ranges if k not in ("t_ambient_c",)]
    lr = {k: (math.log(a), math.log(b)) if k in log_keys else (a, b) for k, (a, b) in ranges.items()}
    samples = sample_parameters(lr, n, method="lhs", seed=seed)
    samples = [{k: (math.exp(v) if k in log_keys else v) for k, v in s.items()} for s in samples]
    with Pool(workers) as pool:
        rows = pool.map(_one, [(mode, s) for s in samples], chunksize=16)
    return [r for r in rows if r is not None]


def rows_to_xy(mode: str, rows: List[Dict[str, float]]) -> Tuple[np.ndarray, np.ndarray]:
    a = {k: np.array([r[k] for r in rows]) for k in rows[0]}
    X = features(mode, a["base_width_mm"], a["base_depth_mm"], a["base_thickness_mm"], a["n_fins"],
                 a["fin_thickness_mm"], a["fin_height_mm"], a["k_w_mk"],
                 a["source_frac_w"] * a["base_width_mm"], a["source_frac_d"] * a["base_depth_mm"],
                 a["t_ambient_c"], a["power_w"], a.get("air_velocity_m_s"))
    ys = [np.log(a["r_base_k_w"])]
    if mode == "forced":
        ys.append(np.log(np.maximum(a["pressure_drop_pa"], 1e-6)))
    return X, np.stack(ys, axis=1).astype(np.float32)


# ── model ────────────────────────────────────────────────────────────────────

@dataclass
class Surrogate:
    mode: str
    model: torch.nn.Module
    x_mean: np.ndarray
    x_std: np.ndarray
    y_mean: np.ndarray
    y_std: np.ndarray
    conformal_log_q: Dict[str, float]      # {"90": q, "95": q} on log R
    report: Dict

    def predict_log(self, X: np.ndarray) -> np.ndarray:
        with torch.no_grad():
            z = torch.as_tensor((X - self.x_mean) / self.x_std, dtype=torch.float32)
            y = self.model(z)
            y = (y.y if hasattr(y, "y") else y).numpy()
        return y * self.y_std + self.y_mean

    def predict(self, X: np.ndarray) -> Dict[str, np.ndarray]:
        y = self.predict_log(X)
        out = {"r_base_k_w": np.exp(y[:, 0])}
        if self.mode == "forced":
            out["pressure_drop_pa"] = np.exp(y[:, 1])
        return out

    def save(self, path: str) -> None:
        torch.save({"mode": self.mode, "state": self.model.state_dict(),
                    "x_mean": self.x_mean, "x_std": self.x_std, "y_mean": self.y_mean,
                    "y_std": self.y_std, "conformal_log_q": self.conformal_log_q,
                    "arch": ARCH, "report": self.report}, path)

    @classmethod
    def load(cls, path: str) -> "Surrogate":
        obj = torch.load(path, map_location="cpu", weights_only=False)
        model = _build(len(FEATURES[obj["mode"]]), len(TARGETS[obj["mode"]]))
        model.load_state_dict(obj["state"])
        model.eval()
        return cls(obj["mode"], model, obj["x_mean"], obj["x_std"], obj["y_mean"], obj["y_std"],
                   obj["conformal_log_q"], obj["report"])


ARCH = {"name": "bench_mlp", "width": 128, "depth": 4, "act": "silu"}


def _build(in_dim: int, out_dim: int) -> torch.nn.Module:
    import pinneapple_neural.architectures  # noqa: F401  (registers the model zoo)
    from pinneapple_neural.architectures.registry import ModelRegistry
    return ModelRegistry.build(ARCH["name"], in_dim=in_dim, out_dim=out_dim, width=ARCH["width"],
                               depth=ARCH["depth"], act=ARCH["act"])


def train(mode: str, rows: List[Dict[str, float]], seed: int = 0, epochs: int = 400) -> Surrogate:
    from torch.utils.data import DataLoader, TensorDataset
    from pinneapple_neural.trainer import TrainConfig, Trainer
    from pinneapple_neural.trainer.lbfgs_finetune import multi_round_lbfgs

    from .trust import surrogate_report

    torch.manual_seed(seed)
    X, Y = rows_to_xy(mode, rows)
    rng = np.random.default_rng(seed)
    idx = rng.permutation(len(X))
    n = len(X)
    n_te, n_cal, n_val = int(0.15 * n), int(0.10 * n), int(0.10 * n)
    te, cal, va, tr = (idx[:n_te], idx[n_te:n_te + n_cal], idx[n_te + n_cal:n_te + n_cal + n_val],
                       idx[n_te + n_cal + n_val:])
    x_mean, x_std = X[tr].mean(0), X[tr].std(0) + 1e-8
    y_mean, y_std = Y[tr].mean(0), Y[tr].std(0) + 1e-8
    zx = lambda a: torch.as_tensor((X[a] - x_mean) / x_std)
    zy = lambda a: torch.as_tensor((Y[a] - y_mean) / y_std)

    def to_loader(a, shuffle):
        ds = TensorDataset(zx(a), zy(a))
        return DataLoader(ds, batch_size=128, shuffle=shuffle,
                          collate_fn=lambda b: {"x": torch.stack([i[0] for i in b]),
                                                "y": torch.stack([i[1] for i in b])})

    model = _build(X.shape[1], Y.shape[1])
    mse = lambda m, y_hat, batch: torch.mean((y_hat - batch["y"]) ** 2)
    log_dir = tempfile.mkdtemp(prefix=f"hs_{mode}_")
    t0 = time.time()
    fit = Trainer(model, mse).fit(
        to_loader(tr, True), to_loader(va, False),
        TrainConfig(epochs=epochs, lr=2e-3, device="cpu", seed=seed, log_dir=log_dir,
                    run_name=mode, physics_aware_validation=False),
    )
    if fit.get("best_path"):
        from pinneapple_neural.trainer.checkpoint import load_checkpoint
        model.load_state_dict(load_checkpoint(fit["best_path"]).model_state)

    # full-batch L-BFGS polish on the training split
    xt, yt = zx(tr), zy(tr)

    def closure_builder():
        def closure():
            out = model(xt)
            return torch.mean(((out.y if hasattr(out, "y") else out) - yt) ** 2)
        return closure

    lb = multi_round_lbfgs(list(model.parameters()), closure_builder, n_rounds=4,
                           n_steps_per_round=200)
    train_s = time.time() - t0
    model.eval()

    sur = Surrogate(mode, model, x_mean, x_std, y_mean, y_std, {}, {})
    # split-conformal on log R using the calibration split
    res = np.abs(sur.predict_log(X[cal])[:, 0] - Y[cal, 0])
    m = len(res)
    for cov in (90, 95):
        level = min(1.0, math.ceil((m + 1) * cov / 100) / m)
        sur.conformal_log_q[str(cov)] = float(np.quantile(res, level))

    history = {"adam": [h["train_total"] for h in fit["history"]],
               "lbfgs_rounds": list(lb.round_losses)}
    sur.report = surrogate_report(
        sur, X=X, Y=Y, split={"train": tr, "val": va, "cal": cal, "test": te},
        history=history, train_seconds=train_s, n_rows=len(rows),
    )
    return sur


def load_surrogates() -> Dict[str, Surrogate]:
    out = {}
    for mode in ("forced", "natural"):
        p = os.path.join(ARTIFACTS, f"surrogate_{mode}.pt")
        if os.path.exists(p):
            out[mode] = Surrogate.load(p)
    return out


def _dataset_path(mode: str) -> str:
    return os.path.join(ARTIFACTS, f"dataset_{mode}.json.gz")


def main(n_forced: int = 6000, n_natural: int = 5000, workers: int = 4, reuse: bool = False) -> None:
    import gzip
    os.makedirs(ARTIFACTS, exist_ok=True)
    for mode, n in (("forced", n_forced), ("natural", n_natural)):
        t = time.time()
        if reuse and os.path.exists(_dataset_path(mode)):
            with gzip.open(_dataset_path(mode), "rt") as f:
                rows = json.load(f)
        else:
            rows = generate_dataset(mode, n, seed={"forced": 1, "natural": 2}[mode], workers=workers)
            with gzip.open(_dataset_path(mode), "wt") as f:
                json.dump(rows, f)
        print(f"[{mode}] {len(rows)} physics samples in {time.time() - t:.0f}s", flush=True)
        sur = train(mode, rows)
        sur.save(os.path.join(ARTIFACTS, f"surrogate_{mode}.pt"))
        with open(os.path.join(ARTIFACTS, f"surrogate_{mode}_report.json"), "w") as f:
            json.dump(sur.report, f, indent=2)
        print(f"[{mode}] verdict: {sur.report['verdict']}", flush=True)


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n-forced", type=int, default=6000)
    ap.add_argument("--n-natural", type=int, default=5000)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--reuse-dataset", action="store_true",
                    help="retrain on the saved physics dataset instead of regenerating it")
    a = ap.parse_args()
    main(a.n_forced, a.n_natural, a.workers, a.reuse_dataset)
